"""empty message

Revision ID: 88412e5ccd33
Revises: bbaf881060eb
Create Date: 2026-05-27 18:33:24.685479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88412e5ccd33'
down_revision = 'bbaf881060eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('shipping_street', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_zip', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_phone', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('shipping_phone')
        batch_op.drop_column('shipping_country')
        batch_op.drop_column('shipping_zip')
        batch_op.drop_column('shipping_state')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_street')
        batch_op.drop_column('shipping_full_name')
        batch_op.drop_column('delivery_method')
        batch_op.drop_column('stripe_session_id')

    # ### end Alembic commands ###
